"""Real spherical-harmonic basis: correctness and UniK3D bit-compatibility.

The Ray Module decodes rays with the same basis UniK3D uses, so its weights can
initialize ours (paper Sec. 3.3).  If this basis drifts from UniK3D's, the
initialization silently means something else -- hence the cross-check below.
"""
from __future__ import annotations

import math
import sys
from pathlib import Path

import pytest
import torch

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from cam3r.sht import SH_DIM, SH_DIM_NO_DC, rsh_cart_3, sh_basis


def _unit(n: int = 512) -> torch.Tensor:
    g = torch.Generator().manual_seed(0)
    v = torch.randn(n, 3, generator=g, dtype=torch.float64)
    return v / v.norm(dim=-1, keepdim=True)


def test_shapes():
    xyz = _unit(17)
    assert rsh_cart_3(xyz).shape == (17, SH_DIM)
    assert sh_basis(xyz).shape == (17, SH_DIM_NO_DC)
    assert SH_DIM == 16 and SH_DIM_NO_DC == 15


def test_drops_only_the_dc_term():
    xyz = _unit(11)
    full = rsh_cart_3(xyz)
    assert torch.allclose(sh_basis(xyz), full[..., 1:])
    # The DC term is the constant 1/(2*sqrt(pi)).
    assert torch.allclose(full[..., 0], torch.full((11,), 0.5 / math.sqrt(math.pi), dtype=torch.float64))


def test_orthonormal_on_the_sphere():
    """<Y_i, Y_j> over S^2 = delta_ij.  Monte-Carlo with 4*pi measure."""
    torch.manual_seed(0)
    n = 400_000
    v = torch.randn(n, 3, dtype=torch.float64)
    v = v / v.norm(dim=-1, keepdim=True)
    Y = rsh_cart_3(v)                       # (n, 16)
    gram = (Y.T @ Y) / n * (4.0 * math.pi)  # E[Y_i Y_j] * 4pi
    assert torch.allclose(gram, torch.eye(SH_DIM, dtype=torch.float64), atol=2e-2)


@pytest.mark.parametrize("degree,expected", [(1, 3), (2, 8), (3, 15)])
def test_degree_truncation(degree, expected):
    assert sh_basis(_unit(5), degree=degree).shape[-1] == expected


def test_rotation_equivariance_of_the_l1_block():
    """The l=1 block is a linear image of (x, y, z), so it rotates with the input."""
    xyz = _unit(64)
    Y = rsh_cart_3(xyz)[:, 1:4]
    # Y_1 = c * (-y, z, -x) in this convention.
    c = 0.48860251190292
    assert torch.allclose(Y, c * torch.stack([-xyz[:, 1], xyz[:, 2], -xyz[:, 0]], -1))


def test_matches_unik3d_reference():
    """Bit-level agreement with the vendored UniK3D basis (weight-init compatibility)."""
    import re

    path = Path(__file__).resolve().parents[2] / "third_party" / "UniK3D" / "unik3d" / "utils" / "sht.py"
    if not path.exists():
        pytest.skip("third_party/UniK3D not vendored")
    # Neither `import unik3d.utils.sht` nor a direct spec-load works here: the
    # package __init__ drags in huggingface_hub/torchvision, and the module's
    # higher-degree functions use py3.9+ `list[...]` annotations at module
    # scope.  Exec just the one autogenerated function we compare against.
    src = re.search(r"^def rsh_cart_3\(.*?^(?=def |\Z)", path.read_text(), re.S | re.M)
    assert src is not None, "rsh_cart_3 not found in UniK3D sht.py"
    ns: dict = {"torch": torch}
    exec(compile(src.group(0), str(path), "exec"), ns)

    xyz = _unit(97).float()
    assert torch.allclose(rsh_cart_3(xyz), ns["rsh_cart_3"](xyz), atol=0, rtol=0)
