# Copyright (c) 2026.
"""Real spherical harmonics in Cartesian form, degrees 0..3.

CAM3R Eq. 2 reconstructs each pixel's ray as an SH expansion

    d_i(u) = sum_{l=1..L} sum_{m=-l..l} c^i_{l,m} Y^m_l(psi(u))   (then L2-normalized)

with ``L <= 3`` (paper Table S3).  The ``l = 0`` term is dropped: it is constant
over the image and would only add a global offset to every ray, which the
subsequent normalization cannot use.  That leaves ``3 + 5 + 7 = 15`` basis
functions -- the same count as UniK3D's angular module emits (deg1/deg2/deg3
heads of width 3/5/7), which is what makes UniK3D weights a valid initialization
for the Ray Module.

The expressions are vendored verbatim from UniK3D's
``unik3d/utils/sht.py`` (itself generated by github.com/cheind/
torch-spherical-harmonics) so the two bases agree exactly; ``cam3r/tests/
test_sht.py`` asserts that agreement whenever ``third_party/UniK3D`` is present.
Index convention: ``Y_l^m`` sits at ``l*(l+1) + m``.
"""
from __future__ import annotations

import torch

SH_DIM = 16        # degrees 0..3 inclusive
SH_DIM_NO_DC = 15  # degrees 1..3 -- what the Ray Module regresses

# Number of coefficients contributed by each degree, in order (l = 1, 2, 3).
SH_DEGREE_WIDTHS = (3, 5, 7)


def rsh_cart_3(xyz: torch.Tensor) -> torch.Tensor:
    """Real SH up to degree 3 for unit vectors ``xyz`` (..., 3) -> (..., 16)."""
    x = xyz[..., 0]
    y = xyz[..., 1]
    z = xyz[..., 2]

    x2 = x**2
    y2 = y**2
    z2 = z**2
    xy = x * y
    xz = x * z
    yz = y * z

    return torch.stack(
        [
            xyz.new_tensor(0.282094791773878).expand(xyz.shape[:-1]),
            -0.48860251190292 * y,
            0.48860251190292 * z,
            -0.48860251190292 * x,
            1.09254843059208 * xy,
            -1.09254843059208 * yz,
            0.94617469575756 * z2 - 0.31539156525252,
            -1.09254843059208 * xz,
            0.54627421529604 * x2 - 0.54627421529604 * y2,
            -0.590043589926644 * y * (3.0 * x2 - y2),
            2.89061144264055 * xy * z,
            0.304697199642977 * y * (1.5 - 7.5 * z2),
            1.24392110863372 * z * (1.5 * z2 - 0.5) - 0.497568443453487 * z,
            0.304697199642977 * x * (1.5 - 7.5 * z2),
            1.44530572132028 * z * (x2 - y2),
            -0.590043589926644 * x * (x2 - 3.0 * y2),
        ],
        -1,
    )


def sh_basis(xyz: torch.Tensor, degree: int = 3) -> torch.Tensor:
    """SH basis with the DC term removed: (..., 3) -> (..., 3/8/15) for l = 1/2/3."""
    if degree not in (1, 2, 3):
        raise ValueError(f"degree must be 1, 2 or 3 (got {degree})")
    keep = sum(SH_DEGREE_WIDTHS[:degree])
    return rsh_cart_3(xyz)[..., 1 : 1 + keep]
